### ISSUE TITLE
Helicopter Transports go Idle at base

### ISSUE THREAD

**Issue by Kutcha313** [SceptreOfficial/Simplex-Support-Services#122] opened 2024-09-25 17:39 UTC
**Describe the bug**
Hello there been testing your SSS DEV and it is awesome. Only seen on thing that randomly keeps happening and that is when a heli transport gets detroyed it will respawn, but when I get in again the interface says Idle no Idle at Base and I can't use it anymore. 

**To Reproduce**
1. Hard to reproduce is is just random. Sometimes I can ues the transports 5 times in a row and all good, then it will freeze on Idle. Other times after the first try.
2. First this happens I would be using Nato helis, then I switched to RHS UH-60. I would take off from carrier then switch location on a roof of a hospital in Altis. Same thing.

I was just wondering if you guys know about this or not, and if I'm just missing something simple.

I will be doing more an idepth test and will send the necessary files later.

Thanks

Fletcher(Steam)

**Comment by SceptreOfficial** [comment] 2024-12-27 08:03
I couldn't reproduce the issue of the transports freezing up, but I did fix the incorrect status update in #130 
Some minor tweaks were made that alter behaviors on respawn, so please let me know if you still encounter unresponsive transports in this context. I'm going to close this issue for now since it's possibly resolved. Feel free to open a new one if the issue persists.

**Closed by SceptreOfficial** 2024-12-27 08:03 UTC
Labels: bug, need info/reproduction
