### ISSUE TITLE
Bug: Holding a smoke makes pick-helicopters think you have popped one

### ISSUE THREAD

**Issue by NortonDK** [SceptreOfficial/Simplex-Support-Services#15] opened 2019-09-26 23:59 UTC
Make a helicopter come to you with pickup order. wait for it to ask for smoke. Hold a smoke in your hand(the ACE way) without popping it makes the helicopter see the smoke(that isnt there) and ask it its the correct one

Mods run:
![image](https://user-images.githubusercontent.com/4981470/65733034-efa48e80-e0cc-11e9-858f-7f4a8169f5c2.png)
https://youtu.be/RNXWgXg-kZE

**Comment by SceptreOfficial** [comment] 2019-09-27 01:26
This is expected behavior, especially in single player.
When you confirm the signal, that is when the helicopter gets the current position of the smoke grenade and lands there. It won't land where it first detected it, so this won't really interfere with anything.

Closing the issue since its not really a bug with SSS.

**Closed by SceptreOfficial** 2019-09-27 01:26 UTC
